### ISSUE TITLE
ifind接口的symbol和vnpy的symbol不一致的问题

### ISSUE THREAD

**Issue by SimpleRealDT** [vnpy/vnpy_ifind#3]
ifind中期货的symbol 都是大写，用rb2205无法获取到数据，需要在
# 生成iFinD合约代码
symbol生成里加.upper()

**Comment by SimpleRealDT** [comment]
EXCHANGE_MAP 少了一个INE的映射 INE在同花顺里还是SHF

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_ifind/pull/4
